# Generated by Django 5.2.11 on 2026-03-02 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('file_type', models.CharField(choices=[('txt', 'Text File'), ('rtf', 'Rich Text Format'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('pptx', 'PowerPoint Presentation'), ('pdf', 'PDF Document'), ('img', 'Image File'), ('jpg', 'JPEG Image'), ('png', 'PNG Image'), ('gif', 'GIF Image'), ('mp3', 'MP3 Audio'), ('avi', 'AVI Video'), ('mp4', 'MP4 Video'), ('avi', 'AVI Video'), ('zip', 'ZIP Archive'), ('rar', 'RAR Archive'), ('7zip', '7-Zip Archive'), ('html', 'HTML File'), ('css', 'CSS File'), ('csv', 'CSV File')], max_length=40)),
                ('size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatmessage')),
            ],
        ),
    ]
