# Generated by Django 5.2.11 on 2026-03-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('txt', 'Text File'), ('rtf', 'Rich Text Format'), ('doc', 'Word Document'), ('docx', 'Word Document'), ('xls', 'Excel Spreadsheet'), ('xlsx', 'Excel Spreadsheet'), ('pptx', 'PowerPoint Presentation'), ('pdf', 'PDF Document'), ('img', 'Image File'), ('jpg', 'JPEG Image'), ('png', 'PNG Image'), ('ico', 'Icon Image'), ('gif', 'GIF Image'), ('mp3', 'MP3 Audio'), ('avi', 'AVI Video'), ('mp4', 'MP4 Video'), ('zip', 'ZIP Archive'), ('xzip', 'ZIP Archive'), ('rar', 'RAR Archive'), ('7zip', '7-Zip Archive'), ('html', 'HTML File'), ('css', 'CSS File'), ('csv', 'CSV File')], max_length=40),
        ),
    ]
